# Generated by Django 5.1.5 on 2025-02-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_testmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testmedia',
        ),
    ]
