# Generated by Django 5.1.5 on 2025-02-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_delete_testmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testomonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('testomonial', models.TextField()),
                ('image', models.ImageField(upload_to='testomonial/')),
                ('rating', models.IntegerField(max_length=1)),
            ],
        ),
    ]
