# Generated by Django 5.1.5 on 2025-02-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_testomonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testomonial',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
